export const listCourseItems = {
  query: `query getCourses($page: Int){
    listCourses(page: $page){
      _id,
      subject,
      level,
      about,
      price_per_month,
      assignments{
        student{
          _id,
          facebook{
            name,
            avatar
          }
        },
        status
      },
      rating{
        author{
          facebook{
            name
          }
        },
        comment,
        stars
      },
      session_in_week{
        day,
        start,
        end
      },
      prefer_location,
      teacher{
        _id,
        facebook{
          avatar                
        }
        tutor{
          display_name,
          contact_email,
          gender
        }
      }
    }
  }`
}
export const getCourseDetail = (id) => ({
  query: `query getCourseDetail($id: ID!) {
    getCourseById(_id: $id) {
      _id,
      subject,
      level,
      about,
      price_per_month,
      city,
      assignments{
        student{
          _id,
          facebook{
            name,
            avatar
          }
        },
        message,
        status
      },
      rating{
        author{
          _id,
          facebook{
            name,
            avatar
          }
        },
        comment,
        stars
      },
      session_in_week{
        day,
        start,
        end
      },
      prefer_location,
      teacher{
        _id,
        facebook{
          avatar                
        }
        tutor{
          display_name,
          contact_email,
          gender,
          dob,
          city,
          subjects,
          education,
          more_info
        }
      }
    }
  }`,
  variables: `{
    "id": "${id}"
  }`
})
export const getProfileDetail = (id) => ({
  query: `query getProfileDetail($id: ID!) {
      getProfileDetail(_id: $id){
        user{
          facebook{
            id,
            avatar,
            token,
            email,
            name
          },
          tutor{
            display_name,  
            contact_email,    
            dob,
            gender,
            education,
            more_info,
            street_address,
            city,
            subjects
          }
        },
        ownedCourses{
          _id,
          subject,
          level,
          about,
          price_per_month,
          prefer_location,
          teacher{
            _id
          }
          session_in_week{
            day,
            start,
            end
          },
          rating{
            author{
              facebook{
                name
              }
            },
            comment,
            stars
          }
        },
        enrolledCourses{
          _id,
          teacher{
            _id,
            facebook{
              name,
              avatar
            }
          },
          assignments{
            student{
              _id
            },
            status
          },
          subject,
          level,
          about,
          price_per_month,
          prefer_location,
          teacher{
            _id,
            facebook{
              name,
              avatar
            }
            tutor{
              display_name
            }
          },
          session_in_week{
            day,
            start,
            end
          },
          rating{
            author{
              facebook{
                name
              }
            },
            comment,
            stars
          }
        }
      }
    }`,
    variables: `{
      "id": "${id}"
    }`
})